org: hackathon2024
app: Hackathon-saude-4.0
service: hackaton-saude-4.0
frameworkVersion: "3"

plugins:
  - serverless-offline
  - serverless-plugin-typescript

custom:
  userTableName: "user-${sls:stage}"
  examTableName: "exam-${sls:stage}"
  vaccineTableName: "vaccine-${sls:stage}"
  serverless-plugin-typescript:
    tsconfig: ./tsconfig.json
    outDir: ./dist
  esbuild:
    bundle: true
    minify: false

provider:
  name: aws
  runtime: nodejs18.x
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - Fn::GetAtt: [UserTable, Arn]
            - Fn::GetAtt: [ExamTable, Arn]
            - Fn::GetAtt: [VaccineTable, Arn]
  environment:
    USER_TABLE: ${self:custom.userTableName}
    EXAM_TABLE: ${self:custom.examTableName}
    VACCINE_TABLE: ${self:custom.vaccineTableName}

functions:
  api:
    handler: src/handler.handler
    events:
      - httpApi: "*"

resources:
  Resources:
    UserTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: userID
            AttributeType: S
        KeySchema:
          - AttributeName: userID
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:custom.userTableName}

    ExamTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: examID
            AttributeType: S
        KeySchema:
          - AttributeName: examID
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:custom.examTableName}

    VaccineTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: userID
            AttributeType: S
        KeySchema:
          - AttributeName: userID
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:custom.vaccineTableName}
